services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-ozon}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-pass}
    ports:
      - "${DB_PORT:-5555}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d ozon" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:4
    container_name: db_migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
    entrypoint: >
      sh -c "migrate -path /migrations -database '${POSTGRES_DSN}' up || true"
    volumes:
      - ./migrations:/migrations:ro
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GQLGEN_VERSION: v0.17.81
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      STORE: pg
      POSTGRES_DSN: ${POSTGRES_DSN}
    ports: ["8080:8080"]
    restart: unless-stopped

volumes:
  dbdata: