package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"PostsAndCommentsMicroservice/graph/generated"
	"PostsAndCommentsMicroservice/graph/model"
	"context"
	"errors"
	"log"
	"time"

	"github.com/google/uuid"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, body string, author string) (*model.Post, error) {
	newPost := &model.Post{
		ID:             uuid.NewString(),
		Title:          title,
		Body:           body,
		Author:         author,
		CommentsClosed: false,
		CreatedAt:      time.Now().UTC(),
	}
	if err := r.Store.CreatePost(ctx, newPost); err != nil {
		return nil, err
	}
	return newPost, nil
}

// ToggleCommentsClosed is the resolver for the toggleCommentsClosed field.
func (r *mutationResolver) ToggleCommentsClosed(ctx context.Context, postID string, closed bool) (*model.Post, error) {
	post, err := r.Store.CloseComments(ctx, postID, closed)
	if err != nil {
		return nil, err
	}
	return post, nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, postID string, parentID *string, body string, author string) (*model.Comment, error) {
	if parentID != nil && *parentID == "" {
		parentID = nil
	}

	post, err := r.Store.GetPost(ctx, postID)
	if err != nil {
		return nil, err
	}
	if post == nil {
		return nil, errors.New("post not found")
	}
	if post.CommentsClosed {
		return nil, errors.New("comments are closed for this post")
	}

	comment := &model.Comment{
		ID:        uuid.NewString(),
		PostID:    postID,
		ParentID:  parentID,
		Author:    author,
		Body:      body,
		CreatedAt: time.Now().UTC(),
	}

	if err := r.Store.CreateComment(ctx, comment); err != nil {
		return nil, err
	}

	log.Printf("[MUT] addComment postID=%s commentID=%s", postID, comment.ID)
	go r.Bus.Publish(postID, *comment)
	return comment, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	posts, err := r.Store.ListPosts(ctx)
	if err != nil {
		return nil, err
	}
	return posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	post, err := r.Store.GetPost(ctx, id)
	if err != nil {
		return nil, err
	}
	return post, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID string, parentID *string, after *string, first *int) (*model.CommentPage, error) {
	limit := 20
	if first != nil && *first > 0 {
		limit = *first
	}

	commentsPage, err := r.Store.ListComments(ctx, postID, parentID, after, limit)
	if err != nil {
		return nil, err
	}
	return commentsPage, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	log.Printf("[SUB] subscribe postID=%s", postID)

	channel := make(chan *model.Comment, 1)

	unsubscribe := r.Bus.Subscribe(
		postID,
		func(comment model.Comment) {
			log.Printf("[SUB] push postID=%s commentID=%s", postID, comment.ID)
			commentCopy := comment
			channel <- &commentCopy
		},
	)

	// отписать клиента, когда он отрубится
	go func() {
		<-ctx.Done()
		log.Printf("[SUB] unsubscribe postID=%s", postID)
		unsubscribe()
		close(channel)
	}()
	return channel, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
