// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string    `json:"id"`
	PostID    string    `json:"postID"`
	ParentID  *string   `json:"parentID,omitempty"`
	Author    string    `json:"author"`
	Body      string    `json:"body"`
	Depth     int       `json:"depth"`
	CreatedAt time.Time `json:"createdAt"`
}

type CommentEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Comment `json:"node"`
}

type CommentPage struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Post struct {
	ID             string    `json:"id"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
	Author         string    `json:"author"`
	CommentsClosed bool      `json:"commentsClosed"`
	CreatedAt      time.Time `json:"createdAt"`
	CommentsCount  int       `json:"commentsCount"`
}

type Query struct {
}

type Subscription struct {
}
